=== TRaSH-Guides/Guides/schemas/cf-groups.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "trash_id": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{32}$"
    },
    "trash_description": {
      "type": "string",
      "minLength": 1
    },
    "default": {
      "type": "string",
      "enum": ["true", "false"]
    },
    "custom_formats": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "trash_id": {
            "type": "string",
            "pattern": "^[a-fA-F0-9]{32}$"
          },
          "required": {
            "type": "boolean"
          },
          "default": {
            "type": "boolean"
          }
        },
        "required": ["name", "trash_id", "required"],
        "additionalProperties": false
      }
    },
    "quality_profiles": {
      "type": "object",
      "properties": {
        "include": {
          "type": "object",
          "patternProperties": {
            "^.+$": {
              "type": "string",
              "pattern": "^[a-fA-F0-9]{32}$"
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "required": ["include"],
      "additionalProperties": false
    }
  },
  "required": ["name", "trash_id", "custom_formats", "quality_profiles"],
  "additionalProperties": false
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf-groups/hdr-formats-hdr10-boost.json
{
  "name": "[HDR Formats] HDR10+ Boost",
  "trash_id": "b29413a7487478fe98228ce79e5689e4",
  "trash_description": "If you prefer HDR10+ releases and have compatible equipment, add the HDR10+ Boost custom format. This custom format prioritizes releases containing HDR10+ over standard HDR releases.",
  "custom_formats": [
    {
      "name": "HDR10+ Boost",
      "trash_id": "caa37d0df9c348912df1fb1d88f9273a",
      "required": true
    }
  ],
  "quality_profiles": {
    "include": {
      "Remux + WEB 2160p": "fd161a61e3ab826d3a22d53f935696dd",
      "Remux 2160p (Alternative)": "dd3cd75deb9645bae838d1c5da6388d5",
      "Remux 2160p (Combined)": "d1d310673359205736b4b84acd5ea8c8",
      "UHD Bluray + WEB": "64fb5f9858489bdac2af690e27c8f42f",
      "[French MULTi.VO] UHD Bluray + WEB": "92ead7022d13a7858d54e328e6a2f8f9",
      "[French MULTi.VO] UHD Remux (2160p)": "1fef28c8c919f31cd86283b1baf527d4",
      "[German] Remux + WEB 2160p": "79faa9943cef2f510b997b1f2a9f3ea6",
      "[German] UHD Bluray + WEB": "27cc3d153c0a799fd139ef1ff4c4cc42",
      "[German] UHD Bluray + WEB (Alternative)": "425da1ba30711b55d2eb371437ec98d7",
      "[SQP] SQP-1 (2160p)": "5128baeb2b081b72126bc8482b2a86a0",
      "[SQP] SQP-1 WEB (2160p)": "e91c9adaca0231493f4af0d571b907f9",
      "[SQP] SQP-2": "c3933358ba2356bafc41524f81471069",
      "[SQP] SQP-3": "2cf36c1f0106ffac993be003ade51865",
      "[SQP] SQP-3 (Audio)": "0ada8e60cc3ddf2733b65de10f4a6c72",
      "[SQP] SQP-4": "013f89e6da27519fe56cf482702a2db9",
      "[SQP] SQP-4 (MA Hybrid)": "7526db7ac0a1f764793fb181864d0222",
      "[SQP] SQP-5": "a7bb1539fd147256b21b1098f3dc2016"
    }
  }
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf-groups/optional-french-audio-version.json
{
    "name": "[Optional] French Audio Version",
    "trash_id": "6a554241c0a7121dfa220dcb22066d0f",
    "trash_description": "French Audio Version",
    "custom_formats": [
        {
            "name": "FanSUB",
            "trash_id": "84f0acbda9c0c9de783894fb66df25aa",
            "required": false
        },
        {
            "name": "FastSUB",
            "trash_id": "ea0bb4b6ba388992fad1092703b5ff7b",
            "required": false
        },
        {
            "name": "VF2",
            "trash_id": "34789ec3caa819f087e23bbf9999daf7",
            "required": false
        },
        {
            "name": "VFB",
            "trash_id": "0ce1e39a4676c6692ce47935278dac76",
            "required": false
        },
        {
            "name": "VFF",
            "trash_id": "2c29a39a4fdfd6d258799bc4c09731b9",
            "required": false
        },
        {
            "name": "VFI",
            "trash_id": "b6816a0e1d4b64bf3550ad3b74b009b6",
            "required": false
        },
        {
            "name": "VFQ",
            "trash_id": "7a7f4e4f58bd1058440236d033a90b67",
            "required": false
        },
        {
            "name": "VOF",
            "trash_id": "7ae924ee9b2f39df3283c6c0beb8a2aa",
            "required": false
        },
        {
            "name": "VOQ",
            "trash_id": "802dd70b856c423a9b0cb7f34ac42be1",
            "required": false
        },
        {
            "name": "VOSTFR",
            "trash_id": "07a32f77690263bb9fda1842db7e273f",
            "required": false
        },
        {
            "name": "VQ",
            "trash_id": "82085412d9a53ba8d8e46fc624eb701d",
            "required": false
        }
    ],
    "quality_profiles": {
        "include": {
            "Base Profile": "e58cf4e090184db3b3d7c79c1a9e9b4a"
        }
    }
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf-groups/streaming-services-uk.json
{
    "name": "[Streaming Services] UK",
    "trash_id": "ddab3095a5d2f436f369263840af34f9",
    "trash_description": "Collection of UK Streaming Services for Sonarr",
    "custom_formats": [
        {
            "name": "4OD",
            "trash_id": "bbcaf03147de0f73be2be4a9078dfa03",
            "required": true
        },
        {
            "name": "ALL4",
            "trash_id": "fcc09418f67ccaddcf3b641a22c5cfd7",
            "required": true
        },
        {
            "name": "IP",
            "trash_id": "dc503e2425126fa1d0a9ad6168c83b3f",
            "required": true
        },
        {
            "name": "ITVX",
            "trash_id": "fa5a16b951004c23e980d2913694a137",
            "required": true
        },
        {
            "name": "MY5",
            "trash_id": "9f72dc1059a6b277c21cee6a1f15f13f",
            "required": true
        },
        {
            "name": "NOW",
            "trash_id": "b66a699fba6f9df91becab798d7502e5",
            "required": true
        }
    ],
    "quality_profiles": {
        "include": {
            "WEB-1080p": "72dae194fc92bf828f32cde7744e51a1",
            "WEB-1080p (Alternative)": "9d142234e45d6143785ac55f5a9e8dc9",
            "WEB-2160p": "d1498e7d189fbe6c7110ceaabb7473e6",
            "WEB-2160p (Alternative)": "dfa5eaae7894077ad6449169b6eb03e0",
            "WEB-2160p (Combined)": "c4cadd6b35b95f62c3d47a408e53e2f7",
            "[German] Anime HD Bluray + WEB": "6fe5937e1dcc2269e23b49eb46dfe6d6",
            "[German] HD Bluray + WEB": "dca7e5e9e99c703bcbdaaa471dd40e98",
            "[German] HD Remux + WEB": "0dd5f085ed61a1e01f6d347779dfa1bc",
            "[German] UHD Bluray + WEB": "3b0fa37fddaaefc931b75f2889d4b4f5",
            "[German] UHD Remux + WEB": "08cececf1840290f6fd490b7d79e8642",
            "[German] UHD Bluray + WEB (Alternative)": "7324309a7d1e10dc0dc2cea6c70ed852",
            "[French MULTi.VF] HD Bluray + WEB (1080p)": "58e8dc75731040612dd6f4ac0676bfd7",
            "[French MULTi.VF] UHD Bluray + WEB (2160p)": "68c8b82ad2b7ea1941fce71eb56421c3",
            "[French MULTi.VO] HD Bluray + WEB (1080p)": "4c48f506c1116a3a57ae33f12346bd15",
            "[French MULTi.VO] UHD Bluray + WEB (2160p)": "6fa7364373e8f06206871d9c20a4fb3e",
            "[French VOSTFR] HD Bluray + WEB (1080p)": "b34c968f58433a38e0e690d42a1dc37e",
            "[French VOSTFR] UHD Bluray + WEB (2160p)": "d6252dce6af535107ed4b03e68052ae8",
            "[Anime] Remux-1080p": "20e0fc959f1f1704bed501f23bdae76f",
            "Base Profile": "e58cf4e090184db3b3d7c79c1a9e9b4a"
        }
    }
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf-groups/streaming-services-misc.json
{
  "name": "[Streaming Services] Miscellaneous",
  "trash_id": "9fc645b3cef52b149ec13ba3972245d1",
  "trash_description": "Collection of Miscellaneous Streaming Services for Radarr",
  "custom_formats": [
    {
      "name": "AUBC",
      "trash_id": "3bf143ecd06f66ed88da4c704350af1d",
      "required": false
    },
    {
      "name": "CBC",
      "trash_id": "d9058beaae2e147183870304dd526761",
      "required": false
    },
    {
      "name": "CRAV",
      "trash_id": "f6ff65b3f4b464a79dcc75950fe20382",
      "required": false
    },
    {
      "name": "OViD",
      "trash_id": "fbca986396c5e695ef7b2def3c755d01",
      "required": false
    },
    {
      "name": "STRP",
      "trash_id": "ab56ccdc473a1f2897c76187ea365be2",
      "required": false
    }
  ],
  "quality_profiles": {
    "include": {
      "HD Bluray + WEB": "d1d67249d3890e49bc12e275d989a7e9",
      "Remux + WEB 1080p": "9ca12ea80aa55ef916e3751f4b874151",
      "Remux + WEB 2160p": "fd161a61e3ab826d3a22d53f935696dd",
      "Remux 2160p (Alternative)": "dd3cd75deb9645bae838d1c5da6388d5",
      "Remux 2160p (Combined)": "d1d310673359205736b4b84acd5ea8c8",
      "UHD Bluray + WEB": "64fb5f9858489bdac2af690e27c8f42f",
      "[Anime] Remux-1080p": "722b624f9af1e492284c4bc842153a38",
      "[French MULTi.VO] HD Bluray + WEB": "2572ce3ea4eef1c19d59e0e20ed1cea7",
      "[French MULTi.VO] HD Remux (1080p)": "c6460a102b312200c095a2d0982e0461",
      "[French MULTi.VO] UHD Bluray + WEB": "92ead7022d13a7858d54e328e6a2f8f9",
      "[French MULTi.VO] UHD Remux (2160p)": "1fef28c8c919f31cd86283b1baf527d4",
      "[French MULTi.VF] HD Bluray + WEB": "500ecc23572575511fd81893777d1e06",
      "[French MULTi.VF] HD Remux (1080p)": "6b93fe45f357e9a94228e5d4658e9bb5",
      "[French MULTi.VF] UHD Bluray + WEB": "e64b266178c7f70e208f493f00e0e50a",
      "[French MULTi.VF] UHD Remux (2160p)": "595bb95c6b6970468880069dce23e1d2",
      "[French VOSTFR] HD Bluray + WEB": "1addc08c4232bc2617684d517df15f75",
      "[French VOSTFR] HD Remux (1080p)": "d98f20924b001e9f6b9595d5440abc87",
      "[French VOSTFR] UHD Bluray + WEB": "525bf0513e2ac22fe116e8d7bec0a6b5",
      "[French VOSTFR] UHD Remux (2160p)": "9b32fc61d8ec83ed131f50f1db80505a",
      "[German] HD Bluray + WEB": "2b90e905c99490edc7c7a5787443748b",
      "[German] HD Remux + WEB": "c13c33fdd2c306266b34cb9946de5919",
      "[German] Remux + WEB 2160p": "79faa9943cef2f510b997b1f2a9f3ea6",
      "[German] UHD Bluray + WEB": "27cc3d153c0a799fd139ef1ff4c4cc42",
      "[German] UHD Bluray + WEB (Alternative)": "425da1ba30711b55d2eb371437ec98d7",
      "[SQP] SQP-1 (1080p)": "0896c29d74de619df168d23b98104b22",
      "[SQP] SQP-1 (2160p)": "5128baeb2b081b72126bc8482b2a86a0",
      "[SQP] SQP-1 WEB (1080p)": "90a3370d2d30cbaf08d9c23b856a12c8",
      "[SQP] SQP-1 WEB (2160p)": "e91c9adaca0231493f4af0d571b907f9",
      "[SQP] SQP-2": "c3933358ba2356bafc41524f81471069",
      "[SQP] SQP-3": "2cf36c1f0106ffac993be003ade51865",
      "[SQP] SQP-3 (Audio)": "0ada8e60cc3ddf2733b65de10f4a6c72",
      "[SQP] SQP-4": "013f89e6da27519fe56cf482702a2db9",
      "[SQP] SQP-4 (MA Hybrid)": "7526db7ac0a1f764793fb181864d0222",
      "[SQP] SQP-5": "a7bb1539fd147256b21b1098f3dc2016",
      "Base Profile": "92e9a65a52ae48478fb8e9f34238d823"
    }
  }
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf-groups/hdr-formats-dv-boost.json
{
    "name": "[HDR Formats] DV Boost",
    "trash_id": "1616617ab3a14397a2b2321bcbda44d1",
    "trash_description": "If you prefer Dolby Vision and have compatible equipment, add the DV Boost custom format. This custom format prioritizes releases containing Dolby Vision over standard HDR releases.",
    "custom_formats": [
        {
            "name": "DV Boost",
            "trash_id": "b337d6812e06c200ec9a2d3cfa9d20a7",
            "required": true
        }
    ],
    "quality_profiles": {
        "include": {
            "Remux + WEB 2160p": "fd161a61e3ab826d3a22d53f935696dd",
            "UHD Bluray + WEB": "64fb5f9858489bdac2af690e27c8f42f",
            "Remux 2160p (Alternative)": "dd3cd75deb9645bae838d1c5da6388d5",
            "Remux 2160p (Combined)": "d1d310673359205736b4b84acd5ea8c8",
            "[German] Remux + WEB 2160p": "79faa9943cef2f510b997b1f2a9f3ea6",
            "[German] UHD Bluray + WEB": "27cc3d153c0a799fd139ef1ff4c4cc42",
            "[German] UHD Bluray + WEB (Alternative)": "425da1ba30711b55d2eb371437ec98d7",
            "[French MULTi.VF] UHD Bluray + WEB": "e64b266178c7f70e208f493f00e0e50a",
            "[French MULTi.VF] UHD Remux (2160p)": "595bb95c6b6970468880069dce23e1d2",
            "[French MULTi.VO] UHD Bluray + WEB": "92ead7022d13a7858d54e328e6a2f8f9",
            "[French MULTi.VO] UHD Remux (2160p)": "1fef28c8c919f31cd86283b1baf527d4",
            "[French VOSTFR] UHD Bluray + WEB": "525bf0513e2ac22fe116e8d7bec0a6b5",
            "[French VOSTFR] UHD Remux (2160p)": "9b32fc61d8ec83ed131f50f1db80505a",
            "[SQP] SQP-1 (2160p)": "5128baeb2b081b72126bc8482b2a86a0",
            "[SQP] SQP-1 WEB (2160p)": "e91c9adaca0231493f4af0d571b907f9",
            "[SQP] SQP-2": "c3933358ba2356bafc41524f81471069",
            "[SQP] SQP-3": "2cf36c1f0106ffac993be003ade51865",
            "[SQP] SQP-3 (Audio)": "0ada8e60cc3ddf2733b65de10f4a6c72",
            "[SQP] SQP-4": "013f89e6da27519fe56cf482702a2db9",
            "[SQP] SQP-4 (MA Hybrid)": "7526db7ac0a1f764793fb181864d0222",
            "[SQP] SQP-5": "a7bb1539fd147256b21b1098f3dc2016",
            "Base Profile": "92e9a65a52ae48478fb8e9f34238d823"
        }
    }
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf-groups/optional-french-audio-version.json
{
    "name": "[Optional] French Audio Version",
    "trash_id": "741d323a2bb14939d1f53659ef0d5e68",
    "trash_description": "French Audio Version",
    "custom_formats": [
        {
            "name": "FanSUB",
            "trash_id": "02e48d30a176c91baf9e15de05e5dc6a",
            "required": false
        },
        {
            "name": "FastSUB",
            "trash_id": "7f9b93f82b7e996391525f2be1d891e0",
            "required": false
        },
        {
            "name": "VF2",
            "trash_id": "29b5f7b1a5f20f64228786c3ab1bdc7d",
            "required": false
        },
        {
            "name": "VFB",
            "trash_id": "b3fb499641d7b3c2006be1d9eb014cb3",
            "required": false
        },
        {
            "name": "VFF",
            "trash_id": "404c08fd0bd67f39b4d8e5709319094e",
            "required": false
        },
        {
            "name": "VFI",
            "trash_id": "52772f1cad6b5d26c2551f79bc538a50",
            "required": false
        },
        {
            "name": "VFQ",
            "trash_id": "b6ace47331a1d3b77942fc18156f6df6",
            "required": false
        },
        {
            "name": "VOF",
            "trash_id": "4cafa20d5584f6ba1871d1b8941aa3cb",
            "required": false
        },
        {
            "name": "VOQ",
            "trash_id": "f7caa1942be5cc547c266bd3dbc2cda9",
            "required": false
        },
        {
            "name": "VOSTFR",
            "trash_id": "9172b2f683f6223e3a1846427b417a3d",
            "required": false
        },
        {
            "name": "VQ",
            "trash_id": "95aa50f71a01c82354a7a2b385f1c4d8",
            "required": false
        }
    ],
    "quality_profiles": {
        "include": {
            "Base Profile": "92e9a65a52ae48478fb8e9f34238d823"
        }
    }
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf-groups/optional-german-miscellaneous.json
{
    "name": "[Optional] German Miscellaneous",
    "trash_id": "9dc92ec4b41b7f38c8e7ecaf7d9dd9bc",
    "trash_description": "Optional Custom Formats: be sure to read the individual descriptions in the guide before adding all of them.",
    "custom_formats": [
        {
            "name": "German 1080p Booster",
            "trash_id": "3bc8df3a71baaac60a31ef696ea72d36",
            "required": false
        },
        {
            "name": "German 2160p Booster",
            "trash_id": "cc7b1e64e2513a6a271090cdfafaeb55",
            "required": false
        },
        {
            "name": "German Subbed",
            "trash_id": "ee425f921dd740621523343bffe82fa3",
            "required": false
        }
    ],
    "quality_profiles": {
        "include": {
            "Base Profile": "92e9a65a52ae48478fb8e9f34238d823"
        }
    }
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf-groups/optional-resolutions.json
{
    "name": "[Optional] Resolutions",
    "trash_id": "b8d2590979210b996913900e4c894825",
    "trash_description": "Optional Custom Formats that cover different resolutions.",
    "custom_formats": [
        {
            "name": "720p",
            "trash_id": "c99279ee27a154c2f20d1d505cc99e25",
            "required": false
        },
        {
            "name": "1080p",
            "trash_id": "290078c8b266272a5cc8e251b5e2eb0b",
            "required": false
        },
        {
            "name": "2160p",
            "trash_id": "1bef6c151fa35093015b0bfef18279e5",
            "required": false
        }
    ],
    "quality_profiles": {
        "include": {
            "Base Profile": "e58cf4e090184db3b3d7c79c1a9e9b4a"
        }
    }
}
