=== TRaSH-Guides/Guides/schemas/guide-only-cf.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "trash_id": {
      "$ref": "base-cf.schema.json#/defs/trash_id"
    },
    "trash_scores": {
      "$ref": "base-cf.schema.json#/defs/trash_scores"
    },
    "trash_regex": {
      "$ref": "base-cf.schema.json#/defs/trash_regex"
    },
    "trash_description": {
      "$ref": "base-cf.schema.json#/defs/trash_description"
    },
    "name": {
      "$ref": "base-cf.schema.json#/defs/name"
    },
    "includeCustomFormatWhenRenaming": {
      "type": "boolean"
    },
    "specifications": {
      "type": "array",
      "items": {
        "anyOf": [
          { "$ref": "specs/release-title-spec.json" },
          { "$ref": "specs/edition-spec.json" },
          { "$ref": "specs/language-spec.json" },
          { "$ref": "specs/indexer-flag-spec.json" },
          { "$ref": "specs/source-spec.json" },
          { "$ref": "specs/resolution-spec.json" },
          { "$ref": "specs/quality-modifier-spec.json" },
          { "$ref": "specs/size-spec.json" },
          { "$ref": "specs/release-group-spec.json" },
          { "$ref": "specs/release-type-spec.json" },
          { "$ref": "specs/year-spec.json" }
        ]
      },
      "minItems": 1
    }
  },
  "required": [
    "trash_id",
    "name",
    "includeCustomFormatWhenRenaming",
    "specifications"
  ],
  "additionalProperties": false
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/4k-remaster.json
{
  "trash_id": "eca37840c13c6ef2dd0262b141a5482f",
  "trash_scores": {
    "default": 25
  },
  "name": "4K Remaster",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "Remaster",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "Remaster"
      }
    },
    {
      "name": "4K",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "4k"
      }
    },
    {
      "name": "Not 4K Resolution",
      "implementation": "ResolutionSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 2160
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/ddplus-atmos.json
{
  "trash_id": "4232a509ce60c4e208d13825b7c06264",
  "trash_scores": {
    "default": 3000
  },
  "name": "DD+ ATMOS",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Dolby Digital Plus",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\bDD[P+]|\\b(e[-_. ]?ac-?3)\\b"
      }
    },
    {
      "name": "ATMOS",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(ATMOS|DDPA)(\\b|\\d)"
      }
    },
    {
      "name": "Not TrueHD",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "True[ .-]?HD"
      }
    },
    {
      "name": "Not DTS",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bDTS(\\b|\\d)"
      }
    },
    {
      "name": "Not Basic Dolby Digital ",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bDD[^a-z+]|(?<!e-)\\b(ac-?3)\\b"
      }
    },
    {
      "name": "Not FLAC",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bFLAC(\\b|\\d)"
      }
    },
    {
      "name": "Not AAC",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bAAC(\\b|\\d)"
      }
    },
    {
      "name": "Not PCM",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\b(l?)PCM(\\b|\\d)"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/language-prefer-original-and-english-and-latino.json
{
  "trash_id": "language-prefer-original-and-english-and-latino",
  "trash_scores": {
    "default": 101
  },
  "trash_description": "Prefer Original and English and Latino",
  "name": "ORIG+ENG+LAT",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Original Language",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": -2
      }
    },
    {
      "name": "English Language",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": 1
      }
    },
    {
      "name": "Latino Language",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": 37
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/upscaled.json
{
  "trash_id": "23297a736ca77c0fc8e70f8edd7ee56c",
  "trash_scores": {
    "default": -10000,
    "german": -35000
  },
  "trash_regex": "https://regex101.com/r/xpT0Md/latest",
  "name": "Upscaled",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "AI Upscales",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "(?<=\\b\\d{3,4}p\\b)(?=.*\\b(HEVC)\\b)(?=.*\\b(AI)\\b)"
      }
    },
    {
      "name": "AIUS",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(AIUS)\\b"
      }
    },
    {
      "name": "Regrade",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b((Upscale)?Re-?graded?)\\b"
      }
    },
    {
      "name": "RW",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(RW)\\b"
      }
    },
    {
      "name": "TheUpscaler",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(The[ ._-]?Upscaler)\\b"
      }
    },
    {
      "name": "Upscaled",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "(?<=\\b\\d{3,4}p\\b).*\\b(AI[ ._-]?Enhanced?|UPS(UHD)?|[Uu]p[Ss]caled?([ ._-]?UHD)?|UpRez)\\b"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/red.json
{
  "trash_id": "c30d2958827d1867c73318a5a2957eb1",
  "trash_scores": {
    "default": 50
  },
  "trash_regex": "https://regex101.com/r/GfOSFe/1",
  "name": "RED",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "YouTube Red",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(red|youtube red)\\b[ ._-]web[ ._-]?(dl|rip)?\\b"
      }
    },
    {
      "name": "RED Rename",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\[(RED)\\b|\\b(RED)\\]"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 4
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/bw.json
{
  "trash_id": "21d9d08e39b05523ec36811ab06b8308",
  "trash_scores": {
    "default": -10000,
    "german": -35000,
    "german-anime": -35000
  },
  "name": "BW",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "Blackout/B&W/Black&Chrome",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "(?<=\\bS\\d+(E\\d+)?\\b).*\\b((B(lack)?[ ._-]?(out|(and|[n&])?[ ._-]?(W(hite)?|Chrome))))\\b(?!$)"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/german-anime-scene.json
{
  "trash_id": "bf40cabd88c0025b03ad511d300d7394",
  "trash_scores": {
    "default": 1700
  },
  "name": "German Anime Scene",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "ONiGiRi",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(ONiGiRi)$"
      }
    },
    {
      "name": "STARS",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(STARS)$"
      }
    },
    {
      "name": "PHM",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(PHM)$"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/language-not-german-english.json
{
  "trash_id": "133589380b89f8f8394320901529bac1",
  "trash_scores": {
      "default": -20000
  },
  "name": "Not German or English",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Not English Language",
      "implementation": "LanguageSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 1
      }
    },
    {
      "name": "Not German Language",
      "implementation": "LanguageSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 4
      }
    },
    {
      "name": "Not German in Title",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "(?i)\\bgerman\\b"
      }
    }
  ]
}
