=== TRaSH-Guides/Guides/schemas/guide-only-cf.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "trash_id": {
      "$ref": "base-cf.schema.json#/defs/trash_id"
    },
    "trash_scores": {
      "$ref": "base-cf.schema.json#/defs/trash_scores"
    },
    "trash_regex": {
      "$ref": "base-cf.schema.json#/defs/trash_regex"
    },
    "trash_description": {
      "$ref": "base-cf.schema.json#/defs/trash_description"
    },
    "name": {
      "$ref": "base-cf.schema.json#/defs/name"
    },
    "includeCustomFormatWhenRenaming": {
      "type": "boolean"
    },
    "specifications": {
      "type": "array",
      "items": {
        "anyOf": [
          { "$ref": "specs/release-title-spec.json" },
          { "$ref": "specs/edition-spec.json" },
          { "$ref": "specs/language-spec.json" },
          { "$ref": "specs/indexer-flag-spec.json" },
          { "$ref": "specs/source-spec.json" },
          { "$ref": "specs/resolution-spec.json" },
          { "$ref": "specs/quality-modifier-spec.json" },
          { "$ref": "specs/size-spec.json" },
          { "$ref": "specs/release-group-spec.json" },
          { "$ref": "specs/release-type-spec.json" },
          { "$ref": "specs/year-spec.json" }
        ]
      },
      "minItems": 1
    }
  },
  "required": [
    "trash_id",
    "name",
    "includeCustomFormatWhenRenaming",
    "specifications"
  ],
  "additionalProperties": false
}

=== TRaSH-Guides/Guides/json/radarr/91-surround.json
{
  "trash_id": "f2aacebe2c932337fe352fa6e42c1611",
  "name": "9.1 Surround",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [{
          "name": "9.1  Surround",
          "implementation": "ReleaseTitleSpecification",
          "negate": false,
          "required": true,
          "fields": {
              "value": "[^0-9]9[ .][0-1]"
          }
      },
      {
          "name": "Not 7.1 Surround",
          "implementation": "ReleaseTitleSpecification",
          "negate": true,
          "required": true,
          "fields": {
              "value": "[^0-9][7-8][ .][0-1]"
          }
      },
      {
          "name": "Not 5.1 Surround",
          "implementation": "ReleaseTitleSpecification",
          "negate": true,
          "required": true,
          "fields": {
              "value": "[^0-9][5-6][ .][0-1]"
          }
      },
      {
          "name": "Not Low Channel Count",
          "implementation": "ReleaseTitleSpecification",
          "negate": true,
          "required": true,
          "fields": {
              "value": "(?<!repac)[^0-9][1-4][ .][0-1]|\\b(Stereo|Mono)\\b"
          }
      }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/cbc.json
{
  "trash_id": "d9058beaae2e147183870304dd526761",
  "name": "CBC",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "CBC",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(CBC)\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 7
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 8
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/line-mic-dubbed.json
{
  "trash_id": "c465ccc73923871b3eb1802042331306",
  "trash_scores": {
    "default": -10000
  },
  "trash_regex": "https://regex101.com/r/6vHBAD/1",
  "name": "Line/Mic Dubbed",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Line Dubbed",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(LD|AC3LD|Line[ .-]?Dubbed)\\b"
      }
    },
    {
      "name": "Mic Dubbed",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(MD|AC3MD|Mic[ .-]?Dubbed)\\b"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/my5.json
{
  "trash_id": "9f72dc1059a6b277c21cee6a1f15f13f",
  "trash_scores": {
    "default": 50
  },
  "name": "MY5",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "MY5",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(my5)\\b[ ._-]web[ ._-]?(dl|rip)?\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 4
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/hd-bluray-tier-01.json
{
  "trash_id": "ed27ebfef2f323e964fb1f61391bcb35",
  "trash_scores": {
    "default": 1800,
    "sqp-1-1080p": 1100,
    "sqp-1-2160p": 1100
  },
  "name": "HD Bluray Tier 01",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "BLURAY",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": 9
      }
    },
    {
      "name": "Not REMUX",
      "implementation": "QualityModifierSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 5
      }
    },
    {
      "name": "Not 2160p",
      "implementation": "ResolutionSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 2160
      }
    },
    {
      "name": "BBQ",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(BBQ)$"
      }
    },
    {
      "name": "BMF",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(BMF)$"
      }
    },
    {
      "name": "c0kE",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(c0kE)$"
      }
    },
    {
      "name": "Chotab",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(Chotab)$"
      }
    },
    {
      "name": "CRiSC",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(CRiSC)$"
      }
    },
    {
      "name": "CtrlHD",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(CtrlHD)$"
      }
    },
    {
      "name": "D-Z0N3",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(D-Z0N3)$"
      }
    },
    {
      "name": "Dariush",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(Dariush)$"
      }
    },
    {
      "name": "decibeL",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(decibeL)$"
      }
    },
    {
      "name": "DON",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(DON)$"
      }
    },
    {
      "name": "EbP",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(EbP)$"
      }
    },
    {
      "name": "EDPH",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(EDPH)$"
      }
    },
    {
      "name": "Geek",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(Geek)$"
      }
    },
    {
      "name": "LolHD",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(LolHD)$"
      }
    },
    {
      "name": "NCmt",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(NCmt)$"
      }
    },
    {
      "name": "PTer",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(PTer)$"
      }
    },
    {
      "name": "TayTO",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(TayTO)$"
      }
    },
    {
      "name": "TDD",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(TDD)$"
      }
    },
    {
      "name": "TnP",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(TnP)$"
      }
    },
    {
      "name": "VietHD",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(VietHD)$"
      }
    },
    {
      "name": "ZQ",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(ZQ)$"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/cpng.json
{
  "trash_id": "d17ea3d84c15299474b76fe85aa02a26",
  "trash_scores": {
    "default": 50
  },
  "name": "CPNG",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "CPNG",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(CPNG)\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 4
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/10bit.json
{
  "trash_id": "a5d148168c4506b55cf53984107c396e",
  "trash_scores": {
    "sqp-1-1080p": -10000,
    "sqp-1-2160p": -10000
  },
  "name": "10bit",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "10bit",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "10[.-]?bit"
      }
    },
    {
      "name": "hi10p",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "hi10p"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/french-lq.json
{
  "trash_id": "48f031e76111f17ea94898f4cdc34fdc",
  "trash_scores": {
    "default": -10000
  },
  "name": "FR LQ",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Ads/Watermarks",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(Bandix|CZ\\d+|EXTREME|GA(√è|I)A|HMiDiMADRiDi|Hush|KILLERMIX|LiBERTAD|LTa?TM|MONiCO|NEWCINE|R(PZ|ZP)|ShowFR|VERCLAM|ViKi47|Wawa-?(city|mania|porno)?|ZW)\\b"
      }
    },
    {
      "name": "Bad/False releases",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(ACOOL|AlioZ|ASPHiXiAS|AViTECH|AZAZE|Balibalo|BLABLASTREAM|DDLFRENCH(ORG)?|FERVEX|FReeZeR|GHOSTSPiRiT|GHZ|GLaDOS|GZR|HEVCBay|JiHeff|KR4K3N|Matmatha|MKVXTEAM|Monchat|NLX5|NOMAD|NORRIS|PiCKLES|PREUMS|qctimb3rlandqc|ReBoT|ROLLED|SCREEN|SHiFT|SKRiN|TicaDow|Tokushi|Tonyk|TOXIC|TUTUTE|UNiKORN|Zombie)\\b"
      }
    },
    {
      "name": "DeTAG/ReTAG",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b((Cpasbien|CPB)|ANONA|AT|bigZT|Boheme|BOL|CINeHD|Cortex91|DOLL4R|Dread[ .-]?Team|Dropse|EZTV([ ._-]re)?|FGT|Firetown|FUN|HDMIDIMADRIDI|JetAnime|L-?O-?L|NewZT|NG|RARBG|STVFRV|SubZero|T9|Time2Watch|TIREXO|Torrent9|WebAnime|YIFY|YTS|ZONE|ZT)\\b"
      }
    },
    {
      "name": "Other reasons",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(AKLHD|ARKRiL|BossBaby|Champion9|Copycomic|CR4ZYTiME|EASPORTS|EliteT|FUNKKY|FZTeam|GOBO2S|HD2|LION|LMPS|LNA3d|MACK4|MeMyl|METALLIKA|MGD|Moorea81|Moviz|Muxman|Mystic|MZC|MZi?SYS|N3TFL1X|NoelMaison|nutella|OMERTA|Papaya|PIKACHU|PULSE|Q7|RELiC|SANCTUAIRE|SHARKS|SP3CTR|Spow|STR4NGE|TeamSuW|TORRiD|TSN999|TVPSLO|Upmix|VATFER|Wakanim|WaNeZt|WINCHESTER|WITA)\\b"
      }
    }
  ]
}
