=== TRaSH-Guides/Guides/schemas/guide-only-cf.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "trash_id": {
      "$ref": "base-cf.schema.json#/defs/trash_id"
    },
    "trash_scores": {
      "$ref": "base-cf.schema.json#/defs/trash_scores"
    },
    "trash_regex": {
      "$ref": "base-cf.schema.json#/defs/trash_regex"
    },
    "trash_description": {
      "$ref": "base-cf.schema.json#/defs/trash_description"
    },
    "name": {
      "$ref": "base-cf.schema.json#/defs/name"
    },
    "includeCustomFormatWhenRenaming": {
      "type": "boolean"
    },
    "specifications": {
      "type": "array",
      "items": {
        "anyOf": [
          { "$ref": "specs/release-title-spec.json" },
          { "$ref": "specs/edition-spec.json" },
          { "$ref": "specs/language-spec.json" },
          { "$ref": "specs/indexer-flag-spec.json" },
          { "$ref": "specs/source-spec.json" },
          { "$ref": "specs/resolution-spec.json" },
          { "$ref": "specs/quality-modifier-spec.json" },
          { "$ref": "specs/size-spec.json" },
          { "$ref": "specs/release-group-spec.json" },
          { "$ref": "specs/release-type-spec.json" },
          { "$ref": "specs/year-spec.json" }
        ]
      },
      "minItems": 1
    }
  },
  "required": [
    "trash_id",
    "name",
    "includeCustomFormatWhenRenaming",
    "specifications"
  ],
  "additionalProperties": false
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/wetv.json
{
  "trash_id": "e0ae51a2508ab62ffb1af027f3717486",
  "trash_scores": {
    "default": 30
  },
  "name": "WETV",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "WETV",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(WETV)\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 4
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/atmos-undefined.json
{
  "trash_id": "417804f7f2c4308c1f4c5d380d4c4475",
  "trash_scores": {
    "default": 3000,
    "sqp-1-1080p": 0,
    "sqp-1-web-1080p": 0,
    "sqp-1-2160p": 0,
    "sqp-1-web-2160p": 0,
    "sqp-4-ma-hybrid": 1420
  },
  "name": "ATMOS (undefined)",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "ATMOS",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\bATMOS(\\b|\\d)"
      }
    },
    {
      "name": "Not AAC",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bAAC(\\b|\\d)"
      }
    },
    {
      "name": "Not Basic Dolby Digital ",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bDD[^a-z+]|(?<!e-)\\b(ac-?3)\\b"
      }
    },
    {
      "name": "Not Dolby Digital Plus",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bDD[P+]|\\b(e[-_. ]?ac-?3)\\b"
      }
    },
    {
      "name": "Not DTS",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bDTS(\\b|\\d)"
      }
    },
    {
      "name": "Not FLAC",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bFLAC(\\b|\\d)"
      }
    },
    {
      "name": "Not PCM",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\b(l?)PCM(\\b|\\d)"
      }
    },
    {
      "name": "Not RlsGrp (Atmos Only)",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\b(W4NK3R|HQMUX)\\b"
      }
    },
    {
      "name": "Not TrueHD",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "True[ .-]?HD"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/with-basl.json
{
  "trash_id": "41e4baea7b10ddefc6609d52f742dacd",
  "trash_regex": "https://regex101.com/r/iCyLwn/1",
  "name": "WiTH BASL",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "Black American Sign Language",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(BASL)\\b"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/hulu.json
{
  "trash_id": "f6cce30f1733d5c8194222a7507909bb",
  "trash_scores": {
    "default": 50
  },
  "name": "HULU",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "Hulu",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(hulu)\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 4
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/language-prefer-spanish.json
{
  "trash_id": "language-prefer-spanish",
  "trash_scores": {
    "default": 10
  },
  "trash_description": "Prefer Language X",
  "name": "Spanish",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Spanish Language",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/hmax.json
{
  "trash_id": "5763d1b0ce84aff3b21038eea8e9b8ad",
  "name": "HMAX",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "HBO Max",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(hmax|hbom|HBO Max)\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 7
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 8
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/ovid.json
{
  "trash_id": "fb1a91cdc0f26f7ca0696e0e95274645",
  "trash_scores": {
    "default": 50
  },
  "trash_regex": "https://regex101.com/r/hWHpjV/1",
  "name": "OViD",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "OViD",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(ovid)\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 4
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/x265-hd.json
{
  "trash_id": "47435ece6b99a0b477caf360e79ba0bb",
  "trash_scores": {
    "default": -10000
  },
  "name": "x265 (HD)",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "x265/HEVC",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "[xh][ ._-]?265|\\bHEVC(\\b|\\d)"
      }
    },
    {
      "name": "Not 2160p",
      "implementation": "ResolutionSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 2160
      }
    }
  ]
}
